name: Build microservice/project
on:
  workflow_call:
    inputs:
      PROJECT_NAME:
        description: "project to build docker image and push."
        type: string
        required: true
      REF:
        description: "branch, tag, or commit SHA from which the project should be build."
        type: string
      TAG:
        description: "artifact version tag"
        type: string
      ENVIRONMENT:
        description: "environment"
        type: string
    secrets:
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    outputs:
      IMAGE: ${{ steps.build.outputs.IMAGE }}
    steps:
      - name: To prove myself
        run: |
            echo "input PROJECT_NAME: ${{ inputs.PROJECT_NAME }}"
            echo "input REF: ${{ inputs.REF }}"
            echo "input TAG: ${{ inputs.TAG }}"
            echo "input ENVIRONMENT: ${{ inputs.ENVIRONMENT }}"
            echo "var APPS: ${{ vars.APPS }}"

      - name: Exit if project not in apps
        run: |
          echo "Project ${{ inputs.PROJECT_NAME }} not in apps  ${{ vars.APPS }}"
          exit 1
        if: (! contains(vars.APPS, inputs.PROJECT_NAME))

      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: "${{ inputs.REF }}"

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Execute make targets to build and push docker image
        id: build
        run: |
            IMAGE=$(TAG=$TAG make -sC ${{ inputs.PROJECT_NAME }} image)
            echo "IMAGE=$IMAGE" | tee -a $GITHUB_ENV
            TAG=$TAG make -C ${{ inputs.PROJECT_NAME }} build
            docker image ls "$IMAGE"
            TAG=$TAG make -C ${{ inputs.PROJECT_NAME }} publish

      - name: Verify docker image
        run: |
            echo "IMAGE is $IMAGE"
            docker image rm "$IMAGE"
            docker pull "$IMAGE"
            docker image ls "$IMAGE"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: "${{env.IMAGE}}"
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        continue-on-error: true
