name: Build microservice/project
on:
  workflow_call:
    inputs:
      PROJECT_NAME:
        description: "project to build docker image and push."
        type: string
        required: true
      REF:
        description: "branch, tag, or commit SHA from which the project should be build."
        type: string
        required: true
      TAG:
        description: "artifact version tag"
        type: string
        required: true
      ENVIRONMENT:
        description: "environment"
        type: string
        required: true
    secrets:
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    outputs:
      IMAGE: ${{ steps.build.outputs.IMAGE }}
    steps:
      - name: To prove myself
        run: |
            #!/usr/bin/env bash
            set -euo pipefail
            echo "input PROJECT_NAME: ${{ inputs.PROJECT_NAME }}"
            echo "input REF: ${{ inputs.REF }}"
            echo "input TAG: ${{ inputs.TAG }}"
            echo "input ENVIRONMENT: ${{ inputs.ENVIRONMENT }}"

      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: "${{ inputs.REF }}"

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Execute make targets to build and push docker image
        id: build
        run: |
            #!/usr/bin/env bash
            set -euo pipefail
            IMAGE=$(TAG=${{ inputs.TAG }} make -sC ${{ inputs.PROJECT_NAME }} image)
            echo "IMAGE=$IMAGE" | tee -a $GITHUB_ENV
            TAG=${{ inputs.TAG }} make -C ${{ inputs.PROJECT_NAME }} build
            docker image ls "$IMAGE"
            TAG=${{ inputs.TAG }} make -C ${{ inputs.PROJECT_NAME }} publish

      - name: Verify docker image
        run: |
            #!/usr/bin/env bash
            set -euo pipefail
            echo "IMAGE is $IMAGE"
            docker image rm "$IMAGE"
            docker pull "$IMAGE"
            docker image ls "$IMAGE"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: "${{env.IMAGE}}"
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        continue-on-error: true
