name: Deploy microservice/project
on:
  workflow_call:
    inputs:
      REF:
        description: "Branch, tag, or commit SHA from which the project should be built."
        type: string
        required: true
      ENVIRONMENT:
        description: "Target environment"
        type: string
        required: true
      TAG:
        description: "Artifact version tag"
        type: string
        required: true

env:
  IMAGE_REGISTRY: deenadayalan27

jobs:
  docker-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Display Inputs and Environment Variables
        run: |
          set -euo pipefail
          echo "REF: ${{ inputs.REF }}"
          echo "ENVIRONMENT: ${{ inputs.ENVIRONMENT }}"
          echo "TAG: ${{ inputs.TAG }}"
          echo "==== Environment Variables ===="
          echo "CONTAINER_HOST: ${{ vars.CONTAINER_HOST }}"
          echo "APPS: ${{ vars.APPS }}"

      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: "${{ inputs.REF }}"

      - name: Generate and Deploy Docker Compose File
        run: |
          set -euo pipefail
          echo "Deploying application(s)..."
          echo "Generating docker-compose.yml for APP: ${{ vars.APPS }} with TAG: ${{ inputs.TAG }}"

          cat <<EOF > docker-compose.yml
          version: '3'
          services:
            dr:
              image: ${{ env.IMAGE_REGISTRY }}/$APP:${{ inputs.TAG }}
              entrypoint:
                - ""
              command:
                - /bin/sh
                - -c
                - |
                  while true; do
                    echo "Hello from dr"
                    sleep 60
                  done
            loki:
              image: ${{ env.IMAGE_REGISTRY }}/loki:${{ inputs.TAG }}
              entrypoint:
                - ""
              command:
                - /bin/sh
                - -c
                - |
                  while true; do
                    echo "Hello from loki"
                    sleep 60
                  done
            thor:
              image: ${{ env.IMAGE_REGISTRY }}/thor:${{ inputs.TAG }}
              entrypoint:
                - ""
              command:
                - /bin/sh
                - -c
                - |
                  while true; do
                    echo "Hello from thor"
                    sleep 60
                  done
          EOF
          echo "Generated docker-compose.yml:"
          cat docker-compose.yml

          # Deploy using Docker Compose
          #docker-compose down
          #docker-compose up -d
          echo "Docker Compose deployment completed."
