name: Deploy microservice/project
on:
  workflow_call:
    inputs:
      REF:
        description: "branch, tag, or commit SHA from which the project should be build."
        type: string
      ENVIRONMENT:
        description: "environment"
        type: string
      TAG:
        description: "artifact version tag"
        type: string

jobs:
  docker-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: check input REF
        run: |
            if [ -z "${{ inputs.REF }}" ]; then
              echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
            else
              echo "BRANCH=${{ inputs.REF }}" >> $GITHUB_ENV
            fi

      - name: To prove myself
        run: |
            echo "input REF: ${{ inputs.REF }}"
            echo "BRANCH:$BRANCH"
            echo "BRANCH:${{env.BRANCH}}"
      
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: "${{env.BRANCH}}"

      - name: Deploy application
        run: |
            echo "deploy application"
            echo "environment variables"
            echo "CONTAINER_HOST: ${{ vars.CONTAINER_HOST }}"
            echo "APPS: ${{ vars.APPS }}"
            echo "APP VERSION/TAG: ${{ inputs.TAG }}"
            echo "copy docker compose file"
            echo "docker-compose down and docker-compose up -d"
