name: Trivy scan

on:
  workflow_call:
    inputs:
      APPS:
        description: "APPS to scan."
        type: string
        required: true
      REF:
        description: "branch, tag, or commit SHA from which the project should be build."
        type: string
        required: true
      ENVIRONMENT:
        description: "environment"
        type: string
        required: true
      TAG:
        description: "artifact version tag"
        type: string
        required: true
      IMAGE_REGISTRY:
        description: "IMAGE REGISTRY"
        type: string
        required: true
    secrets:
      DOCKERHUB_PASSWORD:
        required: true

env:
  IMAGE_REGISTRY: ${{ inputs.IMAGE_REGISTRY }}

jobs:
  trivy-image-scan:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    container:
      image: docker:stable
      options: --privileged
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Install Trivy
        run: |
          apk add --no-cache curl wget bash jq
          export TRIVY_VERSION=$(wget -qO - "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          echo TRIVY_VERSION: $TRIVY_VERSION
          wget --no-verbose https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz -O - | tar -zxvf -
          cat >> contrib/trivy-pr-comment.tpl <<EOF
          {{- range .}}
          {{- range .Vulnerabilities}}
          \n#### {{ .VulnerabilityID | html }} {{ .Severity | html }} {{ .Title | html }}\n
          {{ end }}
          {{- end -}}
          EOF
          mv trivy /usr/local/bin/trivy
          chmod +x /usr/local/bin/trivy
          trivy --version

      - name: Scan docker images
        id: scan
        run: |
          set +e
          EXIT_CODE=0
          echo "Scanning docker images for APPS: ${{ inputs.APPS }}"
          echo "Scanning docker images for TAG: ${{ inputs.TAG }}"
          for app in ${{ inputs.APPS }}; do
            app=$(echo "$app" | xargs)
            echo "Scanning $app"
            trivy image --exit-code 1 --severity HIGH,CRITICAL --format template --template "@contrib/trivy-pr-comment.tpl" --no-progress ${IMAGE_REGISTRY}/${app}:${{ inputs.TAG }} >> trivy.json
            
            if [[ $? -ne 0 ]]; then
              echo "Trivy scan failed for $app"
              EXIT_CODE=1
            fi
          done
          exit $EXIT_CODE

      - name: Report docker image vulnerabilities in PR
        if: ${{ github.event_name == 'pull_request' && steps.scan.conclusion == 'failure' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          #!/bin/bash
          set -eou pipefail
          echo -n '{"body":"### Trivy image scan - Vulnerabilities Detected\nThe following vulnerabilities of HIGH or CRITICAL severity have been detected in the docker iamges. Please resolve these before merging the pull request.\n\n' > result.json
          cat trivy.json | sort | uniq | tr -d '\n'  >> result.json
          echo '"}' >> result.json
          curl -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            ${{ github.event.pull_request.comments_url }} \
            -d @result.json

      - name: Report no docker image vulnerabilities in PR
        if: ${{ github.event_name == 'pull_request' && steps.scan.conclusion == 'success' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          #!/bin/bash
          set -eou pipefail
          echo -n "{\"body\":\"### Trivy image scan - No Image Vulnerabilities Detected\nNo vulnerabilities of HIGH or CRITICAL severity has been detected in the docker images.\"}" > result.json
          curl -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            ${{ github.event.pull_request.comments_url }} \
            -d @result.json

      - name: Check if vulnerabilities were found
        if: ${{ ! cancelled() }}
        run: |
          echo "Checking if vulnerabilities were found"
          cat trivy.json | sort | uniq | tr -d '\n'

  trivy-fs-scan:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    container:
      image: docker:stable
      options: --privileged
    steps:
      - name: Install dependencies
        run: |
          apk add --no-cache curl wget bash jq

      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: "${{ inputs.REF }}"

      - name: Obtain template file
        shell: bash
        run: curl -o trivy-pr-comment.tpl https://raw.githubusercontent.com/domstolene/trivy-pr-report/main/trivy-pr-comment.tpl
    
      - name: Run Trivy for PR report
        uses: aquasecurity/trivy-action@master
        id: scan
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'template'
          template: '@trivy-pr-comment.tpl'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          output: 'trivy.json'
          exit-code: 1
          skip-dirs: ''
          scanners: 'vuln'
          trivy-config: ''

      - name: Report vulnerabilities in PR
        if: ${{ github.event_name == 'pull_request' && steps.scan.outcome == 'failure' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          echo -n "{\"body\":\"### Trivy fs scan - Vulnerabilities detected\nThe following vulnerabilities of HIGH or CRITICAL severity has been detected in the code. Please resolve these before merging the pull request.\n\n" > result.json
          cat trivy.json | sort | uniq | tr -d '\n' >> result.json
          echo "\"}" >> result.json
          curl -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            ${{ github.event.pull_request.comments_url }} \
            -d @result.json
    
      - name: Report no vulnerabilities in PR
        if: ${{ github.event_name == 'pull_request' && steps.scan.outcome == 'success' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          echo -n "{\"body\":\"### Trivy fs scan - No vulnerabilities detected\nNo vulnerabilities of HIGH or CRITICAL severity has been detected in the code.\"}" > result.json
          curl -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            ${{ github.event.pull_request.comments_url }} \
            -d @result.json

      - name: Check if vulnerabilities were found
        if: always()
        run: |
          echo "Checking if vulnerabilities were found"
          cat trivy.json | sort | uniq | tr -d '\n'
