name: Docker Image Scan

on:
  workflow_call:
    inputs:
      REF:
        description: "branch, tag, or commit SHA from which the project should be build."
        type: string
      ENVIRONMENT:
        description: "environment"
        type: string
      TAG:
        description: "artifact version tag"
        type: string
    secrets:
      DOCKERHUB_PASSWORD:
        required: true
env:
  IMAGE_REGISTRY: deenadayalan27

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    env:
      APPS: "dr loki thor"
    container:
      image: docker:stable
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: "${{ inputs.REF }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: debug step
        run: |
          pwd
          ls -rlta

      - name: Install Trivy
        run: |
          apk add --no-cache curl wget bash jq
          export TRIVY_VERSION=$(wget -qO - "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          echo TRIVY_VERSION: $TRIVY_VERSION
          wget --no-verbose https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz -O - | tar -zxvf -
          cat >> contrib/trivy-pr-comment.tpl <<EOF
          {{- range .}}
          {{- range .Vulnerabilities}}
          \n#### {{ .VulnerabilityID | html }} {{ .Severity | html }} {{ .Title | html }}\n{{ .Description | html }}\n
          {{ end }}
          {{- end -}}
          EOF
          mv trivy /usr/local/bin/trivy
          chmod +x /usr/local/bin/trivy
          trivy --version

      - name: Scan images
        id: scan
        run: |
          for APP in $APPS; do
            app=$(echo "$APP" | xargs)
            echo "Scanning $app"
            #trivy image --exit-code 1 --severity HIGH,CRITICAL --format template --template "@contrib/trivy-pr-comment.tpl" --no-progress ${IMAGE_REGISTRY}/${app}:16 >> trivy.json
            echo "=============="
            sleep 5
          done
          trivy image --exit-code 1 --severity HIGH,CRITICAL --format json --output trivy.json --no-progress ${IMAGE_REGISTRY}/dr:16
          
      - name: Report vulnerabilities in PR
        if: github.event_name == 'pull_request' && failure() && steps.scan.outcome == 'failure'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          #!/bin/bash
          set -eou pipefail
          echo -n '{"body":"### Vulnerabilities detected\nThe following vulnerabilities of HIGH or CRITICAL severity have been detected in the code. Please resolve these before merging the pull request.\n\n' > result.json
          jq -r '.Results[] | select(.Vulnerabilities != null) | .Vulnerabilities[] | "#### \(.VulnerabilityID) \(.Severity) \(.Title)\n\(.Description)\n"' trivy.json >> result.json
          echo '"}' >> result.json
          echo "=================================================================result.json================================================================="
          cat result.json
          curl -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            ${{ github.event.pull_request.comments_url }} \
            -d @result.json
    
      - name: Report no vulnerabilities in PR
        if: github.event_name == 'pull_request' && success() && steps.scan.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          #!/bin/bash
          set -eou pipefail
          echo -n "{\"body\":\"### No vulnerabilities detected\nNo vulnerabilities of HIGH or CRITICAL severity has been detected in the code.\"}" > result.json
          curl -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            ${{ github.event.pull_request.comments_url }} \
            -d @result.json
