name: Docker Image Scan

on:
  workflow_call:
    inputs:
      REF:
        description: "branch, tag, or commit SHA from which the project should be build."
        type: string
      ENVIRONMENT:
        description: "environment"
        type: string
      TAG:
        description: "artifact version tag"
        type: string
    secrets:
      DOCKERHUB_PASSWORD:
        required: true
env:
  IMAGE_REGISTRY: deenadayalan27

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    env:
      APPS: dr,loki,thor
    container:
      image: docker:stable
      options: --privileged
    services:
      dind:
        image: docker:stable-dind

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: "${{ inputs.REF }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Trivy scan
        id: trivy-scan
        run: |
          apk add --no-cache curl
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          mkdir -p /root/.cache/trivy-reports
          IFS=',' read -ra APPS_ARRAY <<< "$APPS"
          for app in "${APPS_ARRAY[@]}"; do
            docker pull $app:latest
            trivy image --format json --output /root/.cache/trivy-reports/$app.json $app:latest
          done
