name: Build Deploy Scan and Performance test microservices/project
on:
  workflow_call:
    inputs:
      RUNS_ON:
        type: string
        required: true
        description: runner tag or runner group
      REF:
        type: string
        required: true
        description: "branch"
      TAG:
        description: "artifact version tag"
        type: string
        required: true
      ENVIRONMENT:
        description: "environment"
        type: string
        required: true
      APPS:
        description: "APPS"
        type: string
        required: true
      CONTAINER_HOST:
        description: "CONTAINER_HOST"
        type: string
        required: true
      IMAGE_REGISTRY:
        description: "IMAGE_REGISTRY"
        type: string
        required: true
      VARIABLES_JSON:
        description: "VARIABLES_JSON"
        type: string
        required: true
    secrets:
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  varaibles-parameters:
    runs-on: ${{ inputs.RUNS_ON }}"
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Echo variables and parameters
        run: |
          echo "input RUNS_ON: ${{ inputs.RUNS_ON }}"
          echo "input REF: ${{ inputs.REF }}"
          echo "input TAG: ${{ inputs.TAG }}"
          echo "input ENVIRONMENT: ${{ inputs.ENVIRONMENT }}"
          echo "input APPS: ${{ inputs.APPS }}"
          echo "input CONTAINER_HOST: ${{ inputs.CONTAINER_HOST }}"
          echo "input IMAGE_REGISTRY: ${{ inputs.IMAGE_REGISTRY }}"
          echo "input VARIABLES_JSON: ${{ inputs.VARIABLES_JSON }}"
          echo "input JSON team: $(echo '${{ inputs.VARIABLES_JSON }}' | jq -r '.variables.team')"
      - name: pull-request trigger
        if: github.event_name == 'pull_request'
        run: |
          echo "pull_request trigger"
          echo "pull_request trigger"
      - name: push trigger
        if: github.event_name == 'push'
        run: |
          echo "push trigger"
          echo "push trigger"
      - name: workflow_dispatch trigger
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "workflow_dispatch trigger"
          echo "workflow_dispatch trigger"

  build-dr-project:
    if: contains(inputs.APPS, 'dr')
    uses: the-gymcoder/workflows-catalog/.github/workflows/build-push.yml@init
    with:
      RUNS_ON: ${{ inputs.RUNS_ON }}
      PROJECT_NAME: ${{ toJSON(inputs.VARIABLES_JSON.varaibles.dr) }}
      REF: ${{ inputs.REF }}
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      TAG: ${{ inputs.TAG }}
    secrets: inherit
    needs: 
      - varaibles-parameters

  build-loki-project:
    if: contains(inputs.APPS, 'loki')
    uses: the-gymcoder/workflows-catalog/.github/workflows/build-push.yml@init
    with:
      RUNS_ON: ${{ inputs.RUNS_ON }}
      PROJECT_NAME: loki
      REF: ${{ inputs.REF }}
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      TAG: ${{ inputs.TAG }}
    secrets: inherit
    needs: 
      - varaibles-parameters

  build-thor-project:
    if: contains(inputs.APPS, 'thor')
    uses: the-gymcoder/workflows-catalog/.github/workflows/build-push.yml@init
    with:
      RUNS_ON: ${{ inputs.RUNS_ON }}
      PROJECT_NAME: thor
      REF: ${{ inputs.REF }}
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      TAG: ${{ inputs.TAG }}
    secrets: inherit
    needs: 
      - varaibles-parameters

  scan-projects:
    uses: the-gymcoder/workflows-catalog/.github/workflows/image-scan.yml@init
    with:
      RUNS_ON: ${{ inputs.RUNS_ON }}
      REF: ${{ inputs.REF }}
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      TAG: ${{ inputs.TAG }}
      APPS: ${{ inputs.APPS }}
      IMAGE_REGISTRY: ${{ inputs.IMAGE_REGISTRY }}
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
    needs:
      - build-dr-project
      - build-thor-project
      - build-loki-project

  deploy:
    uses: the-gymcoder/workflows-catalog/.github/workflows/deploy.yml@init
    with:
      RUNS_ON: ${{ inputs.RUNS_ON }}
      REF: ${{ inputs.REF }}
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      TAG: ${{ inputs.TAG }}
      APPS: ${{ inputs.APPS }}
      CONTAINER_HOST: ${{ inputs.CONTAINER_HOST }}
      IMAGE_REGISTRY: ${{ inputs.IMAGE_REGISTRY }}
    secrets: inherit
    needs: 
      - build-dr-project
      - build-thor-project
      - build-loki-project
  
  k6-performance-scan:
    runs-on: ${{ inputs.RUNS_ON }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.REF }}
      - name: Setup K6
        uses: grafana/setup-k6-action@v1
        with:
          k6-version: 0.54.0
          browser: false
      - name: Run k6 test
        uses: grafana/run-k6-action@v1
        with:
          path: http_get.js
    needs:
      - deploy
